### ISSUE TITLE
ci failing, why u no

### ISSUE THREAD

**Issue by sgnl** [sgnl/nodeku#11]

**Comment by ru-lai** [comment]
Hey, 
Could there be an issue because the npm modules were saved from cache from the last npm install commit before you switched to yarn (https://circleci.com/gh/sgnl/nodeku/40 under database), then were restored from the cache in https://circleci.com/gh/sgnl/nodeku/41, and it looks like during the CI build the cache of the node modules keeps being saved during the database phase and reloaded in the machine phase.

I saw that there is an issue in yarn https://github.com/yarnpkg/yarn/issues/3485 with node-sass and other libraries with build artifacts, which occasionally fail at runtime when installed with yarn.

Perhaps nyc has artifacts and you could do a yarn update && npm rebuild nyc and see if it works?

**Comment by sgnl** [comment]
@ru-lai I will try this out thanks dude!
